DROP TABLE `armory_character_stats`; -- 369 MB
DROP TABLE `armory_game_chart`; -- 18 MB
DROP TABLE `battlecl_character_instance_ban`; -- 16 KB
DROP TABLE `battlefield`; -- 14 B
DROP TABLE `character_feed_log`; -- 28 MB
DROP TABLE `character_racechange_log`; -- 12 KB
DROP TABLE `character_rename_log`; -- 86 KB
DROP TABLE `character_transfer`; -- 11 KB
DROP TABLE `character_transfers`; -- 16 KB
DROP TABLE `cheat_damage`; -- 0 B
DROP TABLE `cheat_first_report`; -- 16 KB
DROP TABLE `cheat_proffesion`; -- 0 B
DROP TABLE `cheat_reports`; -- 0 B
DROP TABLE `cheat_teleport`; -- 58 MB
DROP TABLE `cheat_temp_reports`; -- 14 MB
DROP TABLE `custom_transmogrification`; -- 496 KB
DROP TABLE `daily_players_reports`; -- 16 KB
DROP TABLE `houses`; -- 2 KB
DROP TABLE `players_reports_status`; -- 16 KB
DROP TABLE `saved_variables`; -- 16 KB
DROP TABLE `torneo`; -- 0 B
DROP TABLE `War_of_Dummy`; -- 13 B
DROP TABLE `War_of_Dummy_data`; -- 0 B
