ALTER TABLE `characters`
ADD COLUMN `winner` INT(10) UNSIGNED NOT NULL DEFAULT '0',
ADD COLUMN `loser` INT(10) UNSIGNED NOT NULL DEFAULT '0',
ADD COLUMN `rating` INT(10) UNSIGNED NOT NULL DEFAULT '0';
